[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    bblanchon/ArduinoJson@^6.21.4
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BME680 Library
    adafruit/Adafruit SGP30 Sensor
    jgromes/RadioLib@^6.4.0

build_flags =
    -D CORE_DEBUG_LEVEL=3
